githubRepoOwner: alexmirrington
githubRepoName: rules_mypy
githubHost: github.com
requireChecks: true
requireApproval: false
githubRemote: origin
githubBranch: main
remoteBranches: []
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
